name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: redis, pdo_mysql, mbstring, xml, ctype, iconv, intl, pdo_sqlite
          
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        
      - name: Generate key
        run: php artisan key:generate
        
      - name: Run tests
        run: ./vendor/bin/phpunit
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          REDIS_PASSWORD: ""
          REDIS_PREFIX: ""
          BROADCAST_DRIVER: log
          PUSHER_APP_ID: test
          PUSHER_APP_KEY: test
          PUSHER_APP_SECRET: test
          PUSHER_APP_CLUSTER: ap3
